import "./globals.css";
import RightSideBar from "@/components/sidebar/RightSideBar";
import StoreProvider from "./StoreProvider";
import MusicPlayer from "@/components/musicPlayer/MusicPlayer";

import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-side-bar";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Suspense fallback={<p>loading...</p>}>
      <html lang="en">
        <body className={`font-manRope antialiase bg-black`}>
          <StoreProvider>
            <SidebarProvider>
              <main className="w-screen h-screen overflow-auto flex">
                <AppSidebar />

                <section className=" flex-1 "> {children}</section>

                <RightSideBar />
                <MusicPlayer />
              </main>
            </SidebarProvider>
          </StoreProvider>
        </body>
      </html>
    </Suspense>
  );
}
