import LeftSideBar from "@/components/sidebar/LeftSideBar";
import "./globals.css";
import RightSideBar from "@/components/sidebar/RightSideBar";
import StoreProvider from "./StoreProvider";
import MusicPlayer from "@/components/musicPlayer/MusicPlayer";
import { Suspense } from "react";
import LoadingPage from "@/components/home/LoadingPage";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-side-bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <SidebarProvider>
          <body className={`font-manRope antialiase bg-black`}>
            <main className="w-screen h-screen overflow-auto flex">
              <AppSidebar />
              {/* <Suspense fallback={<LoadingPage />}>
                <LeftSideBar />
              </Suspense> */}
              {/* <SidebarTrigger /> */}
              <section className=" flex-1 "> {children}</section>

              <RightSideBar />
              <MusicPlayer />
            </main>
          </body>
        </SidebarProvider>
      </StoreProvider>
    </html>
  );
}
